### ISSUE TITLE
[bug] 没有响应好友申请

### ISSUE THREAD

**Issue by Mcayear** [idanran/koishi-plugin-adapter-red#10]
使用 `koishi-plugin-verifier` 插件批准通过所有好友请求但没有效果。

![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/b0c204ef-c4a7-4310-98cd-95a6957b4386)

## 相关

koishi-plugin-verifier：
https://github.com/koishijs/koishi-plugin-verifier/blob/main/src/index.ts#L58

koishi文档：
https://koishi.chat/zh-CN/api/core/events.html#%E6%88%90%E5%91%98%E7%B1%BB%E4%BA%8B%E4%BB%B6

**Comment by Mcayear** [comment]
因为 `ctx.middleware(async (session, next) => {})` 没有收到**临时会话**的消息。

所以我想让他能够通过好友申请，结果也不行（

**Comment by idranme** [comment]
等有时间我看看

**Comment by idranme** [comment]
这个还得等

**Comment by idranme** [comment]
当前版本适配器（2.5.2）可以收发临时会话消息
