### ISSUE TITLE
私聊无法获取昵称

### ISSUE THREAD

**Issue by windbullet** [idanran/koishi-plugin-adapter-red#12]
session内没有包含昵称的属性
![70FDD8A0-C20B-43C1-903D-10D22DDDC844](https://github.com/idanran/koishi-plugin-adapter-red/assets/47932422/162f8d00-3211-49d3-9dcb-d9dbae2d0be6)
![2F3B7D3E-3BFB-462F-967F-AEE1B7AAC536](https://github.com/idanran/koishi-plugin-adapter-red/assets/47932422/cbfd0008-f775-449e-964e-a9e84565f191)

**Comment by idranme** [comment]
私聊目前没法拿到昵称，这个是由于平台的限制所导致
