### ISSUE TITLE
使用 jsx 插入 image 元素后 p 元素的隔行失效

### ISSUE THREAD

**Issue by eric2788** [idanran/koishi-plugin-adapter-red#13]
源码是这样

```tsx
await session.send(<>
        <image url={data.card.small} />
        <p>名称: {data.name}#{data.tag}</p>
        <p>地区: {regionName(data.region)}</p>
        <p>账户等级: {data.account_level}</p>
        <p>API上次更新: {new Date(data.last_update_raw * 1000)?.toLocaleString() ?? data.last_update}</p>
</>)
```

编译后是这样

```js
await session.send((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)("image", { url: data.card.small }), (0, jsx_runtime_1.jsxs)("p", { children: ["\u540D\u79F0: ", data.name, "#", data.tag] }), (0, jsx_runtime_1.jsxs)("p", { children: ["\u5730\u533A: ", (0, utils_1.regionName)(data.region)] }), (0, jsx_runtime_1.jsxs)("p", { children: ["\u8D26\u6237\u7B49\u7EA7: ", data.account_level] }), (0, jsx_runtime_1.jsxs)("p", { children: ["API\u4E0A\u6B21\u66F4\u65B0: ", new Date(data.last_update_raw * 1000)?.toLocaleString() ?? data.last_update] })] }));
```

但显示出来则没有隔行，全挤在一起

Discord 适配器没有这个问题

**Comment by eric2788** [comment]
ok基本确定了是图片问题，没有图片元素就不会有这个问题

**Comment by eric2788** [comment]
不论使用 h(), 还是在div里面套p再套image, 还是用 md，都有这个问题

**Comment by idranme** [comment]
已解决，请更新至 1.8.2

**Comment by eric2788** [comment]
虽然但是，p元素现在变成任何时候都隔了两行了

**Comment by idranme** [comment]
> 虽然但是，p元素现在变成任何时候都隔了两行了

discord 也是这样

**Comment by idranme** [comment]
我另外修一下吧

**Comment by eric2788** [comment]
> > 虽然但是，p元素现在变成任何时候都隔了两行了
> 
> discord 也是这样

复刻可以这样试试

```
echo -E <image url=xxx /><p>1</p><p>2</p> 
```

1.8.1 版本会挤在一起
1.8.2 则是隔两行

discord目前也是隔兩行
沙盒沒有這問題

如果discord也是这样，不知道会不会是koishi本身的问题，我也不太熟@@

**Comment by idranme** [comment]
discord 写得也有问题

**Comment by idranme** [comment]
改好了，你把适配器更新到 1.8.3 试试。

**Comment by eric2788** [comment]
> 改好了，你把适配器更新到 1.8.3 试试。

ok我回家再試試

**Comment by eric2788** [comment]
> 改好了，你把适配器更新到 1.8.3 试试。

手機版跟電腦板的顯示原來不一樣.... 就算是 1.8.1 版本電腦版顯示還是正常的

btw 1.8.3 版本 手機版顯示沒問題了

**Comment by eric2788** [comment]
@idanran 我問個問題，爲何 video tag 被 comment 了？我現在要如何使用 video 元素？

編輯: 是用 file tag 取代了嗎?

**Comment by idranme** [comment]
> @idanran 我問個問題，爲何 video tag 被 comment 了？我現在要如何使用 video 元素？
> 
> 編輯: 是用 file tag 取代了嗎?

我记得之前是存在一些问题，晚点我会看看能不能用

**Comment by idranme** [comment]
> > @idanran 我問個問題，爲何 video tag 被 comment 了？我現在要如何使用 video 元素？
> > 
> > 編輯: 是用 file tag 取代了嗎?
> 
> 我记得之前是存在一些问题，晚点我会看看能不能用

需要再等等，目前还有问题没解决

**Comment by idranme** [comment]
> @idanran 我問個問題，爲何 video tag 被 comment 了？我現在要如何使用 video 元素？
> 
> 編輯: 是用 file tag 取代了嗎?

最新版可以发送 video 元素了。
