### ISSUE TITLE
接收图片报错

### ISSUE THREAD

**Issue by Haku530** [idanran/koishi-plugin-adapter-red#15]
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/124163849/1ab5cd65-b955-4ad9-9060-33cbae77eadc)
如图，看到接受到的图片url是http://127.0.0.1:5141/red_assets/...，但这个url是不存在的，打不开图片

**Comment by idranme** [comment]
请提供原始图片

**Comment by Haku530** [comment]
随便一张图都会这样报错，和我发的图片无关

**Comment by idranme** [comment]
你的qqnt版本是多少

**Comment by Haku530** [comment]
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/124163849/c5529166-9b56-42f7-99ef-34a5560bc16a)
QQ9.9.2.16183

**Comment by idranme** [comment]
你在koishi用户群吗，麻烦发送「810」，等下我会联系你

**Comment by Haku530** [comment]
我不在，能说下你qq吗，我加你

**Comment by idranme** [comment]
> 我不在，能说下你qq吗，我加你

391463133 麻烦加一下群

**Comment by Haku530** [comment]
我发送啦

**Comment by idranme** [comment]
已在版本 2.2.4 解决
