### ISSUE TITLE
是否可以添加在混合内容间自动加入空格的功能

### ISSUE THREAD

**Issue by Neptune1990** [idanran/koishi-plugin-adapter-red#18]
是否可以添加在混合内容间自动加入空格的功能
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/107494041/1b783f0d-29fd-4684-a6de-fee39a3eae96)

**Comment by idranme** [comment]
这个有什么用呢？

**Comment by Neptune1990** [comment]
有些插件比如sd-extra之类的，要求命令与后面的图片之间要加空格，但是群友习惯了onebot适配器的这个性质，不会去加空格。

**Comment by idranme** [comment]
已在最新版（2.9.1）加入该功能
