### ISSUE TITLE
memes-api报错

### ISSUE THREAD

**Issue by logiest617** [idanran/koishi-plugin-adapter-red#2]
<img width="350" alt="93625fbbe4dcc01c61361bfd3e49deca" src="https://github.com/idanran/koishi-plugin-adapter-red/assets/101518905/b69dd581-22c9-41e4-8334-557297daa95a">
<img width="723" alt="ab4cec26e08317883cb08f56bfd740d8" src="https://github.com/idanran/koishi-plugin-adapter-red/assets/101518905/0de16c07-83a9-454e-95de-83f6c2316ff1">
<img width="948" alt="f2a347b137cd5ccdc85ee05a09540ec0" src="https://github.com/idanran/koishi-plugin-adapter-red/assets/101518905/089b814e-8eed-4291-874f-0912be6ef71f">
<img width="718" alt="37521d30c93ab429b6e3b3390f9e13e6" src="https://github.com/idanran/koishi-plugin-adapter-red/assets/101518905/0acdc910-b922-419d-b18b-bc39f874b0f4">

**Comment by idranme** [comment]
你用哪个版本的适配器呀？

**Comment by idranme** [comment]
我这里测试没问题
