### ISSUE TITLE
[issue] 发送图片及语音时 503 httpcode

### ISSUE THREAD

**Issue by Mcayear** [idanran/koishi-plugin-adapter-red#20]
### 问题

从飞书发送图片时：

![Screenshot_20240202_214340](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/3c275b46-5868-4810-b123-81547ef8a8ef)

从飞书发送语音时：

![Screenshot_20240202_220057](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/22809006-9593-419c-926e-501695d932b9)

### 流程

插件 `nullatom-feedback` 通过 `ctx.middleware(async (session, next) => {});` 获取来自飞书平台的 `session.elements`。

最后使用 `redBot.sendPrivateMessage("2324123456", session.elements)` 来发送给 nt 私聊。

**Comment by idranme** [comment]
先点一下小火箭试试。如果没有解决，那就重启电脑。

**Comment by Mcayear** [comment]
点了小火箭后未果。
重启电脑后也未果。
![Screenshot_20240203_084457](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/289149cc-61ef-4d34-84a2-449dab4cc431)

**Comment by idranme** [comment]
麻烦 QQ 加一下 590104798

**Comment by Mcayear** [comment]
> 麻烦 QQ 加一下 590104798

已经加了，我在群里面发送 `issue20`

**Comment by Mcayear** [comment]
原因，图片链接无法访问。
