### ISSUE TITLE
使用novelai 不会返回等待消息

### ISSUE THREAD

**Issue by logiest617** [idanran/koishi-plugin-adapter-red#3]
red novelai不会回复等候消息 不过可以出图
<img width="334" alt="521e1f18b3072e128f838bea2cedf0bb" src="https://github.com/idanran/koishi-plugin-adapter-red/assets/101518905/7f9030eb-79ed-4334-b3ca-0b8947b4bc88">
<img width="341" alt="09549038ab86c9d0e837860a84faf875" src="https://github.com/idanran/koishi-plugin-adapter-red/assets/101518905/7528267d-442d-43c7-aaf4-41723fd435de">

**Comment by idranme** [comment]
已解决
