### ISSUE TITLE
无法识别群聊

### ISSUE THREAD

**Issue by logiest617** [idanran/koishi-plugin-adapter-red#4]
dialogue是一个问答插件
dialogue-context是一个上下文插件，他会判断触发指令的群聊是否为白名单
<img width="336" alt="385ef677f58a7ac2034d494a91026933" src="https://github.com/idanran/koishi-plugin-adapter-red/assets/101518905/708ad52b-b11d-4d0a-887b-c7da79eabf7d">
我在群聊写入dialogue，发现dialogue无法判断这条消息来自群聊，因此出现截图的情况，正常情况下是默认允许当前群聊

**Comment by logiest617** [comment]
补充：日志正常，没有报错

**Comment by idranme** [comment]
已解决
