### ISSUE TITLE
转发消息

### ISSUE THREAD

**Issue by story-x** [idanran/koishi-plugin-adapter-red#5]
大佬你好，能否支持转发消息
现在发转发消息是分开发，单条分开导致系统检测非正常操作。。。

消息log
[{"type":"node","data":[{"type":"node","data":[{"type":"text","data":"[角色]记录获取成功，更新0条\n[武器]记录获取成功，更新0条\n[常驻]记录获取成功，更新0条"},{"type":"text","data":"[角色]记录获取成功，更新0条\n[武器]记录获取成功，更新0条\n[常驻]记录获取成功，更新0条"},{"type":"text","data":"抽卡记录更新完成，您还可回复\n【#武器记录】统计武器池数据\n【#角色统计】按卡池统计数据\n【#导出记录】导出记录数据"}]}]}]

发出来是这样的
![399361e663ed7c3027f29cad4ff27636](https://github.com/idanran/koishi-plugin-adapter-red/assets/45375162/ebacafa5-bcfb-4b4f-86a3-74b58cae74c2)

导致后续
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/45375162/e131c192-b97f-4fae-acdd-fbd9c9b55989)

**Comment by idranme** [comment]
有时间我看看

**Comment by idranme** [comment]
你用的是哪个插件？

**Comment by story-x** [comment]
用的是： [gscore-adapter ](https://github.com/GithubCin/gscore-adapter) 
原来用chronocat转发消息是这样回的 
![e366c0b549ed0f9c241b8dda8834a42e](https://github.com/idanran/koishi-plugin-adapter-red/assets/45375162/af0dcfb5-2e2a-4957-85af-711b443afa95)

**Comment by idranme** [comment]
你看看其它平台的适配器是不是分开发的

**Comment by idranme** [comment]
我感觉分开发才是正确的行为

**Comment by story-x** [comment]
没有转发消息，我也感觉分开发是正确的行为，能否控制一下分开发的频率，1s发10条系统会检测

**Comment by idranme** [comment]
等我研究下

**Comment by idranme** [comment]
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/96647698/6f50f537-7cfa-4d2e-89d7-a781f38414d4)

**Comment by idranme** [comment]
你把这个关了试试

**Comment by story-x** [comment]
关了也是一样的，我这是发消息太快给系统检测到了，传了个消息数组过去，一口气分单条全发出去了

**Comment by idranme** [comment]
> 关了也是一样的，我这是发消息太快给系统检测到了，传了个消息数组过去，一口气分单条全发出去了

能把数组发我看看吗

**Comment by idranme** [comment]
https://koishi.chat/zh-CN/api/message/elements.html#%E6%B6%88%E6%81%AF

**Comment by idranme** [comment]
”`<message>` 元素的基本用法是表示一条消息。“

**Comment by story-x** [comment]
> > 关了也是一样的，我这是发消息太快给系统检测到了，传了个消息数组过去，一口气分单条全发出去了
> 
> 能把数组发我看看吗

log是这样的
2023-08-08 22:08:20 [I] gscore-adapter 
{"bot_id":"red","bot_self_id":"16","target_type":"group","target_id":"847","content":[{"type":"node","data":[{"type":"node","data":[{"type":"text","data":"[角色]记录获取成功，更新0条\n[武器]记录获取成功，更新0条\n[常驻]记录获取成功，更新0条"},{"type":"text","data":"[角色]记录获取成功，更新0条\n[武器]记录获取成功，更新0条\n[常驻]记录获取成功，更新0条"},{"type":"text","data":"抽卡记录更新完成，您还可回复\n【#武器记录】统计武器池数据\n【#角色统计】按卡池统计数据\n【#导出记录】导出记录数据"}]}]}]}

**Comment by idranme** [comment]
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/96647698/2887fc70-8d29-4620-8b4c-3e805e53c06e)

**Comment by idranme** [comment]
可以个测试的吗

**Comment by idranme** [comment]
算了

**Comment by idranme** [comment]
你还是找那个插件的作者吧

**Comment by idranme** [comment]
这个应该是那个插件的正常的行为

**Comment by idranme** [comment]
https://koishi.chat/zh-CN/api/message/elements.html#%E6%AE%B5%E8%90%BD

可以让插件作者考虑换用这个

**Comment by story-x** [comment]
需要插件分开传消息吗？可以在处理数组元素的时候增加100-200ms 的延时不

**Comment by idranme** [comment]
可以让插件合在一起发

**Comment by idanran** [comment]
https://koishi.chat/zh-CN/api/core/session.html#session-sendqueued
或者可以让插件使用这个 API

**Comment by story-x** [comment]
> 可以让插件合在一起
