### ISSUE TITLE
适配sendMessage

### ISSUE THREAD

**Issue by Mcayear** [idanran/koishi-plugin-adapter-red#6]
大大有适配 [bot#sendMessage](https://koishi.chat/zh-CN/api/core/bot.html#bot-sendmessage) 和 [bot#sendPrivateMessage](https://koishi.chat/zh-CN/api/core/bot.html#bot-sendprivatemessage) 的计划吗

**Comment by idranme** [comment]
当前版本是支持的

**Comment by Mcayear** [comment]
看起来是 red 那边不能发送 image

**Comment by idranme** [comment]
> 看起来是 red 那边不能发送 image

请问你的图片是什么格式

**Comment by Mcayear** [comment]
> > 看起来是 red 那边不能发送 image
> 
> 请问你的图片是什么格式

链接形式。比如httpcat插件的猫图（
插件发送图片消息 red 那边不能正常处理。

**Comment by Mcayear** [comment]
如图

![Screenshot_20230819_225926_edit_21390042852931](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/7d1f4622-154e-40ec-a0a4-a863c9ba56de)


我看onebot中频道id是 `private:QQNumber` 形式
![Screenshot_20230819_230414](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/532506b1-5a61-4027-822c-0127c2513267)

**Comment by idranme** [comment]
> 如图
> 
> ![Screenshot_20230819_225926_edit_21390042852931](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/7d1f4622-154e-40ec-a0a4-a863c9ba56de)
> 
> 
> 我看onebot中频道id是 `private:QQNumber` 形式
> ![Screenshot_20230819_230414](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/532506b1-5a61-4027-822c-0127c2513267)
> 

下个版本会做的

**Comment by idranme** [comment]
> > 如图
> > 
> > ![Screenshot_20230819_225926_edit_21390042852931](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/7d1f4622-154e-40ec-a0a4-a863c9ba56de)
> > 
> > 
> > 我看onebot中频道id是 `private:QQNumber` 形式
> > ![Screenshot_20230819_230414](https://github.com/idanran/koishi-plugin-adapter-red/assets/48203962/532506b1-5a61-4027-822c-0127c2513267)
> > 
> 
> 下个版本会做的

考虑了一下，感觉没有做的必要

**Comment by idranme** [comment]
> > > 看起来是 red 那边不能发送 image
> > 
> > 请问你的图片是什么格式
> 
> 链接形式。比如httpcat插件的猫图（
> 插件发送图片消息 red 那边不能正常处理。

已解决，请更新至 1.0.18。
