### ISSUE TITLE
消息发不出来

### ISSUE THREAD

**Issue by story-x** [idanran/koishi-plugin-adapter-red#8]
更新了1.0.19后消息发不出来了（好像base64的图片全会转），1.0.17可以正常发送

![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/45375162/babe8fb8-f9cf-490d-b2a9-6702d3a4968d)

ffmpeg 环境变量也配了
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/45375162/15f68ae1-ff25-4b39-b497-a9e53f269322)

**Comment by idranme** [comment]
重启电脑试试

**Comment by story-x** [comment]
重启就好了，感谢感谢
