### ISSUE TITLE
无法使用Dialogue实现正则匹配艾特功能

### ISSUE THREAD

**Issue by asasdsaweasd** [idanran/koishi-plugin-adapter-red#9]
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/47250180/6f43d349-811c-4539-a63f-be9449c0be83)
我想实现以上功能 在测试中一模一样并不可以
测试了一下如果把艾特作为回答的话 数据库里的值是`<at id="qq号" name="群昵称"/>`
是否是这个原因导致不支持?
测试语句：`# "^$m(.+)$" 你好 -x -E`
### 相关
Dialogue https://dialogue.koishi.chat
原帖子 https://forum.koishi.xyz/t/topic/1042
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/47250180/ad242ce0-e48a-4c1c-b484-e3843df5f44a)

**Comment by idranme** [comment]
在沙盒能正常使用吗

**Comment by asasdsaweasd** [comment]
> 在沙盒能正常使用吗

我不知道在沙盒里如何艾特

**Comment by asasdsaweasd** [comment]
![image](https://github.com/idanran/koishi-plugin-adapter-red/assets/47250180/e5771de9-3ace-4f0a-b92a-cc771b52dc48)
这种是可以的

**Comment by idranme** [comment]
那我也没办法了

**Comment by asasdsaweasd** [comment]
> 那我也没办法了

阿?为什么 是什么问题导致的

**Comment by idranme** [comment]
> > 那我也没办法了
> 
> 阿?为什么 是什么问题导致的

不知道，建议问一下插件作者

**Comment by idranme** [comment]
> > > 那我也没办法了
> > 
> > 阿?为什么 是什么问题导致的
> 
> 不知道，建议那个插件的仓库问问
